name: altair_experiments
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - python=3.6.5
  - numpy
  - scipy
  - pandas
  - matplotlib
  - jupyter
  - ipython
  - jupyterlab
  - pyyaml

  # Put any conda dependencies here
  - pip:
    # Put any pip dependencies here (and no conda ones anywhere below)
    - tornado>=5.0  # Required to stop luigi from breaking jupyter
    - requests
    - boto3
    - ratelim
    - geopandas
    - altair
    - vega
    - vega_datasets

  # Tooling requirements (don't edit)
    - tqdm
    - pyyaml
    - tables
    - black
    - blackcellmagic
    - pymysql
    - sqlalchemy
    - click
    - Sphinx
    - sphinxcontrib.napoleon
    - coverage
    - awscli
    - flake8
  - python-dotenv>=0.5.1
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - jq
  - pytest
